version: '3'
services:
  flask:
    build: ./backend
    container_name: backend-flask
    environment:
      - FLASK_DEBUG=False
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./backend:/backend
    ports:
      - "80:80"
    command: python app.py