version: '3'
services:
  flask:
    build: ./backend
    container_name: backend-flask
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./backend:/backend
    ports:
      - "49784:49784"
    command: python app.py